// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug logging
console.log('[Supabase Client] Initializing...', {
  url: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 20)}...` : 'MISSING',
  key: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'MISSING',
  env: import.meta.env.MODE,
  allEnvKeys: Object.keys(import.meta.env)
});

// Use fallback values to prevent app crash if env vars are missing
const FALLBACK_URL = 'https://placeholder.supabase.co';
const FALLBACK_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDUxOTI4MDAsImV4cCI6MTk2MDc2ODgwMH0.placeholder';

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = `Missing Supabase environment variables:
    VITE_SUPABASE_URL: ${SUPABASE_URL ? 'Set' : 'MISSING'}
    VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY ? 'Set' : 'MISSING'}
    
    Available env vars: ${Object.keys(import.meta.env).join(', ')}
    
    Please check your deployment platform environment variables configuration.`;
  
  console.error('[Supabase Client]', errorMsg);
  console.error('[Supabase Client] Using fallback values - app will not function properly!');
  
  // Show error on page after React loads
  if (typeof document !== 'undefined') {
    setTimeout(() => {
      const root = document.getElementById('root');
      if (root && root.children.length === 0) {
        root.innerHTML = `
          <div style="padding: 40px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: linear-gradient(135deg, #1e1e2e 0%, #2d1b4e 100%); color: #fff; min-height: 100vh;">
            <div style="max-width: 800px; margin: 0 auto;">
              <h1 style="color: #ff6b6b; font-size: 32px; margin-bottom: 20px; display: flex; align-items: center; gap: 12px;">
                <span style="font-size: 48px;">⚠️</span>
                Environment Variables Missing
              </h1>
              <div style="background: rgba(255, 107, 107, 0.1); border: 2px solid #ff6b6b; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
                <pre style="background: rgba(0,0,0,0.3); padding: 20px; border-radius: 8px; overflow-x: auto; font-size: 14px; line-height: 1.6;">${errorMsg}</pre>
              </div>
              <div style="background: rgba(139, 92, 246, 0.1); border: 2px solid #8b5cf6; border-radius: 12px; padding: 24px;">
                <h2 style="color: #8b5cf6; margin-top: 0; margin-bottom: 16px;">How to Fix:</h2>
                <ol style="line-height: 1.8; padding-left: 24px;">
                  <li>Go to <strong>Vercel/Netlify Dashboard → Your Project → Settings → Environment Variables</strong></li>
                  <li>Add these variables with the <strong>exact names</strong>:
                    <ul style="margin-top: 8px; margin-bottom: 8px;">
                      <li><code style="background: rgba(0,0,0,0.3); padding: 2px 8px; border-radius: 4px;">VITE_SUPABASE_URL</code></li>
                      <li><code style="background: rgba(0,0,0,0.3); padding: 2px 8px; border-radius: 4px;">VITE_SUPABASE_PUBLISHABLE_KEY</code></li>
                    </ul>
                  </li>
                  <li>Check <strong>all environments</strong> (Production, Preview, Development) for each variable</li>
                  <li>Go to <strong>Deployments</strong> → <strong>Redeploy</strong></li>
                  <li><strong>CRITICAL:</strong> Clear cache when redeploying</li>
                </ol>
              </div>
            </div>
          </div>
        `;
      }
    }, 1000);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with actual values or fallbacks
export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
