// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug logging
console.log('[Supabase Client] Initializing...', {
  url: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 20)}...` : 'MISSING',
  key: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'MISSING',
  env: import.meta.env.MODE,
  allEnvKeys: Object.keys(import.meta.env)
});

// Use fallback values to prevent app crash if env vars are missing
const FALLBACK_URL = 'https://placeholder.supabase.co';
const FALLBACK_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDUxOTI4MDAsImV4cCI6MTk2MDc2ODgwMH0.placeholder';

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = `Missing Supabase environment variables (using fallback - this is expected during Firebase migration):
    VITE_SUPABASE_URL: ${SUPABASE_URL ? 'Set' : 'MISSING'}
    VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY ? 'Set' : 'MISSING'}`;
  
  console.warn('[Supabase Client]', errorMsg);
  console.warn('[Supabase Client] Using fallback values - Supabase features will not work (expected during Firebase migration)');
  
  // Don't show error page since we're migrating to Firebase
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with actual values or fallbacks
export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
